GPIO:
  PA1:
    Label: IMU_INT
    Signal: GPXTI1
    GPXTI: true
  PA4:
    Label: IMU_CS
    Signal: GPIO_Output
  PC12:
    Label: KEY2
    Signal: GPXTI12
    GPXTI: true
  PC9:
    Label: DXL_DIR
    Signal: GPIO_Output
  PE4:
    Label: LED3
    Signal: GPIO_Output
  PE5:
    Label: LED2
    Signal: GPIO_Output
  PE6:
    Label: SW2
    Signal: GPIO_Input
  PF14:
    Label: BUZZER_SIG
    Signal: GPIO_Output
  PF15:
    Label: DXL_PWR_EN
    Signal: GPIO_Output
  PG10:
    Label: LED4
    Signal: GPIO_Output
  PG11:
    Label: SW1
    Signal: GPIO_Input
  PG12:
    Label: LED1
    Signal: GPIO_Output
  PG3:
    Label: KEY1
    Signal: GPXTI3
    GPXTI: true
  PG9:
    Label: LED_RUN
    Signal: GPIO_Output
Peripherals:
  TIM:
    TIM1: {}
  ADC:
    ADC1:
      ContinuousMode: true
      RegularConversions:
      - ADC_CHANNEL_VREFINT
      - ADC_CHANNEL_VBAT
      Channels:
      - ADC_CHANNEL_VREFINT
      - ADC_CHANNEL_VBAT
      DMA: ENABLE
      dma:
        dma: &id001
          request_id: '5'
          peripheral: ADC1
          dma_type: DMA
          stream: DMA2_Stream4
          direction: MEMORY
          periph_inc: false
          mem_inc: false
          periph_align: halfword
          mem_align: halfword
          mode: Normal
          priority: Low
          fifo: Disabled
    ADC3:
      ContinuousMode: true
      RegularConversions:
      - ADC_CHANNEL_10
      Channels:
      - ADC_CHANNEL_10
      DMA: ENABLE
      dma:
        dma: &id002
          request_id: '4'
          peripheral: ADC3
          dma_type: DMA
          stream: DMA2_Stream0
          direction: MEMORY
          periph_inc: false
          mem_inc: false
          periph_align: halfword
          mem_align: halfword
          mode: Circular
          priority: Low
          fifo: Disabled
  SPI:
    SPI1:
      BaudRate: 6.75 MBits/s
      Direction: SPI_DIRECTION_2LINES
  USART:
    USART2:
      Mode: Asynchronous
      dma:
        dma_rx: &id003
          request_id: '2'
          peripheral: USART2_RX
          dma_type: DMA
          stream: DMA1_Stream5
          direction: MEMORY
          periph_inc: false
          mem_inc: false
          periph_align: byte
          mem_align: byte
          mode: Normal
          priority: Low
          fifo: Disabled
        dma_tx: &id004
          request_id: '3'
          peripheral: USART2_TX
          dma_type: DMA
          stream: DMA1_Stream6
          direction: PERIPH
          periph_inc: false
          mem_inc: false
          periph_align: byte
          mem_align: byte
          mode: Normal
          priority: Low
          fifo: Disabled
      DMA_RX: ENABLE
      DMA_RX_TYPE: DMA
      DMA_TX: ENABLE
      DMA_TX_TYPE: DMA
    USART3:
      Mode: Asynchronous
      dma:
        dma_rx: &id005
          request_id: '0'
          peripheral: USART3_RX
          dma_type: DMA
          stream: DMA1_Stream1
          direction: MEMORY
          periph_inc: false
          mem_inc: false
          periph_align: byte
          mem_align: byte
          mode: Normal
          priority: Low
          fifo: Disabled
        dma_tx: &id006
          request_id: '1'
          peripheral: USART3_TX
          dma_type: DMA
          stream: DMA1_Stream3
          direction: PERIPH
          periph_inc: false
          mem_inc: false
          periph_align: byte
          mem_align: byte
          mode: Normal
          priority: Low
          fifo: Disabled
      DMA_RX: ENABLE
      DMA_RX_TYPE: DMA
      DMA_TX: ENABLE
      DMA_TX_TYPE: DMA
  CAN:
    CAN2:
      BaudRate: '1000000'
      TimeSeg1: CAN_BS1_15TQ
      TimeSeg2: CAN_BS2_2TQ
      AutoRetransmission: false
      AutoWakeup: false
  USB:
    USB_OTG_FS:
      IPParameters:
      - VirtualMode
      VirtualMode: Device_Only
  IWDG:
    IWDG:
      Prescaler: IWDG_PRESCALER_256
      Enabled: true
  I2C: {}
DMA:
  Requests:
    '0': USART3_RX
    '1': USART3_TX
    '2': USART2_RX
    '3': USART2_TX
    '4': ADC3
    '5': ADC1
    sNb: '6'
  Configurations:
    ADC1_5: *id001
    ADC3_4: *id002
    USART2_RX_2: *id003
    USART2_TX_3: *id004
    USART3_RX_0: *id005
    USART3_TX_1: *id006
Timebase:
  Source: TIM13
  IRQ: TIM8_UP_TIM13_IRQn
Mcu:
  Family: STM32F7
  Type: STM32F746ZGT6
FreeRTOS:
  RTOS: FreeRTOS
  Enabled: false
  AllocationMethod: null
  MemPoolSize: null
  CorePresent: null
  Tasks:
    defaultTask:
      Priority: '0'
      StackSize: 256B
      EntryFunction: StartDefaultTask
      Type: Default
  Heap: null
  Features: []
