terminal_source: usb_otg_fs_cdc
software_timer:
  priority: 2
  stack_depth: 1024
SPI:
  spi1:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_section: .dma_buffer
    dma_enable_min_size: 3
USART:
  usart2:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: .dma_buffer
    tx_queue_size: 5
  usart3:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: .dma_buffer
    tx_queue_size: 5
ADC:
  adc1:
    buffer_size: 32
    dma_section: .dma_buffer
    vref: 3.3
  adc3:
    buffer_size: 32
    dma_section: .dma_buffer
    vref: 3.3
CAN:
  CAN2:
    queue_size: 5
USB:
  usb_otg_fs:
    enable: true
    ep0_packet_size: 64
    tx_buffer_size: 128
    rx_buffer_size: 128
    rx_fifo_size: 256
    tx_fifo_size: 128
    dma_section: ''
    cdc_tx_fifo_size: 128
    cdc_rx_fifo_size: 128
    cdc_queue_size: 3
    vid: 7504
    pid: 24985
    bcd: 256
    manufacturer: XRobot
    product: STM32 XRUSB USB_OTG_FS CDC Demo
    serial: XRUSB-DEMO-
Terminal:
  read_buff_size: 32
  max_line_size: 32
  max_arg_number: 5
  max_history_number: 5
  run_as_thread: true
  thread_stack_depth: 1024
  thread_priority: 3
SYSTEM: FreeRTOS
IWDG:
  iwdg:
    timeout_ms: 1000
    feed_interval_ms: 250
Watchdog:
  run_as_thread: false
  feed_interval_ms: 250
FlashLayout:
  model: STM32F746ZGT6
  flash_base: '0x08000000'
  flash_size_kb: 1024
  sectors:
  - index: 0
    address: '0x08000000'
    size_kb: 32
  - index: 1
    address: '0x08008000'
    size_kb: 32
  - index: 2
    address: '0x08010000'
    size_kb: 32
  - index: 3
    address: '0x08018000'
    size_kb: 32
  - index: 4
    address: '0x08020000'
    size_kb: 128
  - index: 5
    address: '0x08040000'
    size_kb: 256
  - index: 6
    address: '0x08080000'
    size_kb: 256
  - index: 7
    address: '0x080C0000'
    size_kb: 256
device_aliases:
  power_manager:
    type: PowerManager
    aliases:
    - power_manager
  IMU_INT:
    type: GPIO
    aliases:
    - IMU_INT
  IMU_CS:
    type: GPIO
    aliases:
    - IMU_CS
  KEY2:
    type: GPIO
    aliases:
    - KEY2
  DXL_DIR:
    type: GPIO
    aliases:
    - DXL_DIR
  LED3:
    type: GPIO
    aliases:
    - LED3
  LED2:
    type: GPIO
    aliases:
    - LED2
  SW2:
    type: GPIO
    aliases:
    - SW2
  BUZZER_SIG:
    type: GPIO
    aliases:
    - BUZZER_SIG
  DXL_PWR_EN:
    type: GPIO
    aliases:
    - DXL_PWR_EN
  LED4:
    type: GPIO
    aliases:
    - LED4
  SW1:
    type: GPIO
    aliases:
    - SW1
  LED1:
    type: GPIO
    aliases:
    - LED1
  KEY1:
    type: GPIO
    aliases:
    - KEY1
  LED_RUN:
    type: GPIO
    aliases:
    - LED_RUN
  adc1_adc_channel_vrefint:
    type: ADC
    aliases:
    - adc1_adc_channel_vrefint
  adc1_adc_channel_vbat:
    type: ADC
    aliases:
    - adc1_adc_channel_vbat
  adc3_adc_channel_10:
    type: ADC
    aliases:
    - adc3_adc_channel_10
  spi1:
    type: SPI
    aliases:
    - spi1
  usart2:
    type: UART
    aliases:
    - usart2
  usart3:
    type: UART
    aliases:
    - usart3
  can2:
    type: CAN
    aliases:
    - can2
  usb_otg_fs_cdc:
    type: UART
    aliases:
    - usb_otg_fs_cdc
  iwdg:
    type: Watchdog
    aliases:
    - iwdg
  database:
    type: Database
    aliases:
    - database
  ramfs:
    type: RamFS
    aliases:
    - ramfs
  terminal:
    type: Terminal<32, 32, 5, 5>
    aliases:
    - terminal
